version: "3"

services:
    app-postgresql:
        container_name: app-postgresql
        build:
            context: ./postgresql
            dockerfile: Dockerfile
        restart: always
        environment:
            TZ: ${APP_TZ:?err}
            POSTGRES_PASSWORD: ${PGSQL_ROOT_PASS:?err}
            POSTGRES_USER_DB: ${PGSQL_DATA:?err}
            POSTGRES_USER_NAME: ${PGSQL_USER:?err}
            POSTGRES_USER_PASSWORD: ${PGSQL_PASS:?err}
            POSTGRES_HOST_AUTH_METHOD: "md5"
        volumes:
            - app-db-postgre:/var/lib/postgresql/data
        expose:
            - 5432
        networks:
            - default-network
    app-pgadmin:
        image: dpage/pgadmin4
        restart: always
        environment:
            PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL:?err}
            PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD:?err}
        ports:
            - 5050:80
        depends_on:
            - app-postgresql
        networks:
            - default-network
    app-python:
        container_name: app-python
        build:
            context: ./first_django
            dockerfile: Dockerfile
        restart: always
        command: uwsgi --http :8000 --module ${APP_PATH:?err}.wsgi
        environment:
            TZ: ${APP_TZ:?err}
            CHOKIDAR_USEPOLLING: true
            APP_SECRET_KEY: ${APP_SECRET_KEY:?err}
            POSTGRES_HOST: app-postgresql
            POSTGRES_PORT: 5432
            POSTGRES_USER_DB: ${PGSQL_DATA:?err}
            POSTGRES_USER_NAME: ${PGSQL_USER:?err}
            POSTGRES_USER_PASSWORD: ${PGSQL_PASS:?err}
        volumes:
            - app-site:/app
        expose:
            - 8000
        networks:
            - default-network
    app-nodejs:
        container_name: app-nodejs
        build:
            context: ./nodejs
            dockerfile: Dockerfile
        restart: always
        stdin_open: true
        tty: true
        environment:
            TZ: ${APP_TZ:?err}
            CHOKIDAR_USEPOLLING: true
            APP_VUE: ${APP_VUE:?err}
        volumes:
            - app-site-vue:/root
        networks:
            - default-network
    app-nginx:
        container_name: app-nginx
        build:
            context: ./nginx
            dockerfile: Dockerfile
        restart: always
        environment:
            TZ: ${APP_TZ:?err}
            CHOKIDAR_USEPOLLING: true
        volumes:
            - app-site:/usr/share/nginx/app
        ports:
            - 8081:80
            - 8082:8082
        depends_on:
            - app-postgresql
            - app-pgadmin
            - app-python
            - app-nodejs
        networks:
            - default-network
volumes:
    app-site:
        driver: local
        driver_opts:
            type: none
            device: $PWD/${APP_PATH:?err}
            o: bind
    app-site-vue:
        driver: local
        driver_opts:
            type: none
            device: $PWD/${APP_PATH:?err}/${APP_VUE:?err}
            o: bind
    app-db-postgre:
        driver: local
        driver_opts:
            type: none
            device: $PWD/${PGSQL_PATH:?err}
            o: bind
networks:
    default-network:
        name: ${APP_NAME:?err}-network