version: "3"

services:
    app-postgresql:
        container_name: app-postgresql
        build:
            context: ./postgresql
            dockerfile: Dockerfile
        restart: always
        environment:
            POSTGRES_PASSWORD: ${PGSQL_ROOT_PASS:?err}
            POSTGRES_USER_DB: ${PGSQL_DATA:?err}
            POSTGRES_USER: ${PGSQL_USER:?err}
            POSTGRES_USER_PASSWORD: ${PGSQL_PASS:?err}
        volumes:
            - app-db-postgre:/var/lib/postgresql/data
        expose:
            - 8000
        networks:
            - default-network
    app-python:
        container_name: app-python
        build:
            context: ./first_django
            dockerfile: Dockerfile
        restart: always
        command: uwsgi --http :8000 --module ${APP_PATH:?err}.wsgi
        volumes:
            - app-site:/app
        expose:
            - 8000
        networks:
            - default-network
    app-nodejs:
        container_name: app-nodejs
        build:
            context: ./nodejs
            dockerfile: Dockerfile
        restart: always
        stdin_open: true
        tty: true
        volumes:
            - app-site:/app
        networks:
            - default-network
    app-nginx:
        container_name: app-nginx
        build:
            context: ./nginx
            dockerfile: Dockerfile
        restart: always
        volumes:
            - app-site:/usr/share/nginx/app
        ports:
            - 8081:80
            - 442:443
        depends_on:
            - app-postgresql
            - app-python
            - app-nodejs
        networks:
            - default-network
volumes:
    app-site:
        driver: local
        driver_opts:
            type: none
            device: $PWD/${APP_PATH:?err}
            o: bind
    app-db-postgre:
        driver: local
        driver_opts:
            type: none
            device: $PWD/${PGSQL_PATH:?err}
            o: bind
networks:
    default-network:
        name: ${APP_NAME:?err}-network