#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE USER ${POSTGRES_USER_NAME} WITH PASSWORD '${POSTGRES_USER_PASSWORD}';
    CREATE DATABASE ${POSTGRES_USER_DB} OWNER '${POSTGRES_USER_NAME}';
    GRANT ALL PRIVILEGES ON DATABASE ${POSTGRES_USER_DB} TO ${POSTGRES_USER_NAME};
EOSQL